[package]
name = "ogurpchik"
version = "0.3.0"
edition = "2024"
authors = ["ignatternyev54@gmail.com"]
license = "MIT"
description = "A transport-agnostic RPC framework for stream and memory-based communication. Built with high-performance primitives to deliver medium-performance results."
keywords = ["rpc", "windows", "linux", "ipc"]

[dependencies]

compio = { version = "0.18.0", features = ["net", "io-compat", "process", "macros", "time"] }
socket2 = "0.6.2"


anyhow = "1.0.100"
tracing = { version = "0.1.44", features = ["release_max_level_warn"] }
futures = "0.3.31"
hmac = "0.12.1"
sha2 = "0.10.9"
tracing-subscriber = "0.3.22"
bytes = "1.11.1"
kanal = { version = "0.1.1", features = ["async"] }
dashmap = "6.1.0"
affinity = "0.1.2"
num_cpus = "1.17.0"
oneshot = "0.1.13"
smallvec = "1.15.1"
local-sync = "0.1.1"
lazy_static = "1.5.0"

rkyv = { version = "0.8.14", features = ["bytecheck", "std"], optional = true }
serde = { version = "1.0.228", features = ["derive"] }
bitcode = { version = "0.6.9", features = ["serde"], optional = true }
rustc-hash = "2.1.1"
iceoryx2 = { version = "0.8.1", optional = true }

dhat = { version = "0.3", optional = true }

uuid = { version = "1.20.0", features = ["v4", "serde"] }
serde_json = "1.0.149"
object-pool = "0.6.0"
anymap = "0.12.1"
getrandom = "0.4.2"


[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = [
    "Win32_System_Performance",
    "Win32_NetworkManagement", "Win32_NetworkManagement_IpHelper", "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock", "Win32_System_Threading", "Win32_System_Hypervisor", "Win32_System_Registry"] }

winreg = "0.55.0"
widestring = "1.2.1"
winapi = { version = "0.3.9", features = ["libloaderapi", "combaseapi", "minwindef", "ntdef"] }

[target.'cfg(unix)'.dependencies]
libc = "1.0.0-alpha.2"
inotify = "0.11"

[features]

rkyv-codec = ["dep:rkyv"]
bitcode-codec = ["dep:bitcode"]

shm = ["dep:iceoryx2"]
stream = []

tcp = ["stream"]
vsock = ["stream"]
uds = ["stream"]
npipe = ["stream", "compio/fs"]

all = [
    "rkyv-codec",
    "bitcode-codec",
    "shm",
    "tcp",
    "uds",
    "vsock",
    "npipe",
    "stream"
]

dhat-heap = ["dep:dhat"]

[profile.release]
split-debuginfo = "packed"
lto = "thin"
codegen-units = 1
